import { test, expect,chromium } from '@playwright/test';

test.setTimeout(130_000); 
test('Contact Us Form', async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 1000 });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://automationexercise.com/test_cases');
  await page.getByRole('button', { name: 'Consent' }).click();
  await page.getByRole('link', { name: 'Test Case 6: Contact Us Form' }).click();
  await page.locator('#collapse6').getByText('Launch browser').click();
  await page.getByRole('link', { name: '\'http://automationexercise.' }).click();
  await page.getByRole('link', { name: ' Contact us' }).click();
  await page.getByRole('heading', { name: 'Get In Touch' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('robert');
  await page.getByRole('textbox', { name: 'Email', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('robitest');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('robittest');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('robittest@gmail,com');
  await page.getByRole('textbox', { name: 'Subject' }).click();
  await page.getByRole('textbox', { name: 'Subject' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Subject' }).fill('VS CODE');
  await page.getByRole('textbox', { name: 'Subject' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Your Message Here' }).click();
  await page.getByRole('textbox', { name: 'Your Message Here' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Your Message Here' }).fill('MI AM PRINS URECHILE IN EL MAMA LUI');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Capture.PNG');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Email', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email', exact: true }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('robittest@gmail.com');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: ' Home' }).click();
  await page.getByRole('link', { name: 'Website for automation' }).click();
});