import { test, expect, chromium } from '@playwright/test';
test.setTimeout(120_000);
test('Register and delete account on automationexercise.com', async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 800 });
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://automationexercise.com/test_cases');
  await page.getByRole('button', { name: 'Consent' }).click();
  await page.getByRole('link', { name: 'Test Case 1: Register User' }).click();
  await page.getByRole('link', { name: '\'http://automationexercise.' }).click();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByRole('heading', { name: 'New User Signup!' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).dblclick();
  await page.getByRole('textbox', { name: 'Name' }).fill('robert');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('robyzew@gmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByText('Enter Account Information').click();
  await page.getByText('Title Mr. Mrs.').click();
  await page.getByRole('radio', { name: 'Mr.' }).check();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('roby15oct');
  await page.locator('#days').selectOption('15');
  await page.locator('#months').selectOption('10');
  await page.locator('#years').selectOption('2003');
  await page.getByLabel('Sign up for our newsletter!').check();
  await page.getByLabel('Receive special offers from our partners!').check();
  await page.getByRole('textbox', { name: 'First name *' }).fill('Robert');
  await page.getByRole('textbox', { name: 'Last name *' }).fill('Balan');
  await page.getByRole('textbox', { name: 'Company', exact: true }).fill('Nagarro');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('Aleea vegetatiei nr 5');
  await page.getByRole('textbox', { name: 'Address 2' }).fill('Aleea vegetatiei nr 5');
  await page.getByLabel('Country *').selectOption('Israel');
  await page.getByRole('textbox', { name: 'State *' }).fill('romania');
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('Timisoara');
  await page.locator('#zipcode').fill('1234');
  await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('0730809254');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('Account Created!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.getByText('Logged in as robert').click();
  await page.getByRole('listitem').filter({ hasText: 'Delete Account' }).click();
  await page.getByText('Account Deleted!').click();

  await browser.close();
});
